"""
題庫模組 ── 新增/修改題目都在這裡

題目格式：
{
    "q"      : "題目文字（支援 \\n 換行）",
    "opts"   : ["選項1", "選項2", "選項3", "選項4"],
    "ans"    : 正確答案編號(1~4),
    "explain": "答題後顯示的解說",
    "diff"   : 1  # 1=簡單 2=普通 3=挑戰
}

新增章節：在 CHAPTERS dict 加入新的 key，
         同時把 key 加到 CHAPTER_ORDER list 末尾即可。
"""

CHAPTERS = {

    # ──────────────────────────────────────────────────
    "variables": {
        "title"     : "🟫 第一關：變數與資料型別",
        "color_name": "yellow",
        "questions" : [
            {
                "q"      : "Steve 想記錄血量 20，下面哪行程式正確？",
                "opts"   : ["hp = 20", "20 = hp", "hp == 20", "var hp = 20"],
                "ans"    : 1,
                "explain": "賦值用 =，左邊是變數名稱，右邊是值。",
                "diff"   : 1,
            },
            {
                "q"      : "執行 print(type(42)) 會印出什麼？",
                "opts"   : ["<class 'str'>", "<class 'float'>",
                            "<class 'int'>", "<class 'bool'>"],
                "ans"    : 3,
                "explain": "42 是整數，type() 回傳 <class 'int'>。",
                "diff"   : 1,
            },
            {
                "q"      : "Steve 的名字要存成字串，哪個寫法正確？",
                "opts"   : ["name = Steve", 'name = "Steve"',
                            "name = (Steve)", "name == 'Steve'"],
                "ans"    : 2,
                "explain": "字串要用引號（單引號或雙引號）包起來。",
                "diff"   : 1,
            },
            {
                "q"      : "is_alive = True，這個變數是什麼型別？",
                "opts"   : ["str（字串）", "int（整數）",
                            "float（浮點數）", "bool（布林值）"],
                "ans"    : 4,
                "explain": "True / False 是 bool 布林值，表示是或否。",
                "diff"   : 1,
            },
            {
                "q"      : "下面哪個變數名稱是合法的？",
                "opts"   : ["2sword", "my-sword", "my_sword", "my sword"],
                "ans"    : 3,
                "explain": "變數不能以數字開頭、不能有空格或連字號，但可以用底線 _。",
                "diff"   : 1,
            },
            {
                "q"      : "print(type('hello')) 會印出什麼？",
                "opts"   : ["<class 'int'>", "<class 'str'>",
                            "<class 'list'>", "<class 'char'>"],
                "ans"    : 2,
                "explain": "'hello' 是字串，type() 回傳 <class 'str'>。",
                "diff"   : 1,
            },
            {
                "q"      : "x = 3.14，x 是什麼型別？",
                "opts"   : ["int", "str", "float", "double"],
                "ans"    : 3,
                "explain": "有小數點的數字是 float（浮點數）。Python 沒有 double 型別。",
                "diff"   : 1,
            },
            {
                "q"      : "a = 5\na = a + 3\nprint(a)\n印出什麼？",
                "opts"   : ["5", "3", "8", "a + 3"],
                "ans"    : 3,
                "explain": "a 先是 5，再 +3 變成 8，最後印出 8。變數可以被重新賦值。",
                "diff"   : 2,
            },
            {
                "q"      : "a, b = 1, 2\na, b = b, a\nprint(a)\n印出什麼？",
                "opts"   : ["1", "2", "a", "錯誤"],
                "ans"    : 2,
                "explain": "Python 可以用一行交換兩個變數。a, b = b, a 後，a=2, b=1。",
                "diff"   : 2,
            },
            {
                "q"      : "下列哪個是正確的浮點數？",
                "opts"   : ["42", "'3.14'", "3.14", "True"],
                "ans"    : 3,
                "explain": "3.14 有小數點，是 float。42 是 int，'3.14' 是 str，True 是 bool。",
                "diff"   : 1,
            },
            {
                "q"      : "level = 10\nlevel += 5\nprint(level)\n印出什麼？",
                "opts"   : ["10", "5", "15", "level"],
                "ans"    : 3,
                "explain": "+= 是加法賦值。level += 5 等於 level = level + 5，結果是 15。",
                "diff"   : 2,
            },
            {
                "q"      : "sword = 'diamond'\nprint(type(sword))\n印出什麼？",
                "opts"   : ["<class 'int'>", "<class 'float'>",
                            "<class 'str'>", "<class 'diamond'>"],
                "ans"    : 3,
                "explain": "'diamond' 是字串，所以 type() 回傳 <class 'str'>。",
                "diff"   : 1,
            },
        ],
    },

    # ──────────────────────────────────────────────────
    "io": {
        "title"     : "💬 第二關：輸入輸出 & 字串",
        "color_name": "cyan",
        "questions" : [
            {
                "q"      : "要讓玩家輸入名字，應該用哪個函式？",
                "opts"   : ["print()", "input()", "scan()", "read()"],
                "ans"    : 2,
                "explain": "input() 等使用者輸入文字後按 Enter，並回傳一個字串。",
                "diff"   : 1,
            },
            {
                "q"      : 'name = "Steve"\nprint(f"Hello, {name}!") 印出什麼？',
                "opts"   : ["Hello, {name}!", "Hello, name!",
                            "Hello, Steve!", 'f"Hello, Steve!"'],
                "ans"    : 3,
                "explain": "f-string 會把 {} 裡的變數替換成實際的值。",
                "diff"   : 1,
            },
            {
                "q"      : 'print("鑽石" * 3) 印出什麼？',
                "opts"   : ["鑽石 * 3", "鑽石鑽石鑽石", "9", "錯誤"],
                "ans"    : 2,
                "explain": "字串乘以整數，會重複該字串 N 次。",
                "diff"   : 1,
            },
            {
                "q"      : 'len("creeper") 的結果是？',
                "opts"   : ["5", "6", "7", "8"],
                "ans"    : 3,
                "explain": "creeper 有 c-r-e-e-p-e-r 共 7 個字母。",
                "diff"   : 1,
            },
            {
                "q"      : "input() 永遠回傳的資料型別是？",
                "opts"   : ["int", "float", "str", "bool"],
                "ans"    : 3,
                "explain": "input() 永遠回傳字串（str）。要當數字用時先 int() 或 float() 轉換。",
                "diff"   : 1,
            },
            {
                "q"      : 'print("Hello" + " " + "Steve") 印出什麼？',
                "opts"   : ["Hello+Steve", "Hello Steve", "HelloSteve", "錯誤"],
                "ans"    : 2,
                "explain": "字串用 + 串接，中間那個 \" \" 是一個空格字串。",
                "diff"   : 1,
            },
            {
                "q"      : '"minecraft".upper() 的結果是？',
                "opts"   : ["Minecraft", "MINECRAFT", "minecraft", "MineCraft"],
                "ans"    : 2,
                "explain": ".upper() 把字串所有字母轉成大寫。",
                "diff"   : 1,
            },
            {
                "q"      : 'int("42") 之後，型別是什麼？',
                "opts"   : ["str", "float", "int", "bool"],
                "ans"    : 3,
                "explain": "int() 把字串或浮點數轉成整數型別。",
                "diff"   : 1,
            },
            {
                "q"      : 'print(f"{5 * 3} 個鑽石") 印出什麼？',
                "opts"   : ["5 * 3 個鑽石", "{5 * 3} 個鑽石", "15 個鑽石", "錯誤"],
                "ans"    : 3,
                "explain": "f-string 的 {} 裡可以放運算式，5*3=15，所以印出 15 個鑽石。",
                "diff"   : 2,
            },
            {
                "q"      : 'print("HP:", 20) 印出什麼？',
                "opts"   : ["HP:20", "HP: 20", "HP,20", '"HP:", 20'],
                "ans"    : 2,
                "explain": "print() 的多個參數之間自動加一個空格，所以是 HP: 20。",
                "diff"   : 2,
            },
            {
                "q"      : 'x = input("血量：")\ntype(x) 是什麼？',
                "opts"   : ["int（因為輸入數字）", "str（永遠是字串）",
                            "float", "看使用者輸入什麼就是什麼"],
                "ans"    : 2,
                "explain": "不管輸入什麼，input() 永遠回傳 str！要當數字用必須 int(x) 轉換。",
                "diff"   : 2,
            },
            {
                "q"      : '"hello world".capitalize() 的結果是？',
                "opts"   : ["HELLO WORLD", "Hello World", "Hello world", "hello world"],
                "ans"    : 3,
                "explain": "capitalize() 只把第一個字母大寫，其餘小寫，結果是 Hello world。",
                "diff"   : 3,
            },
        ],
    },

    # ──────────────────────────────────────────────────
    "if": {
        "title"     : "⚔️  第三關：條件判斷 if/elif/else",
        "color_name": "red",
        "questions" : [
            {
                "q"      : "hp = 3，要判斷「血量低於5就跑路」，程式怎麼寫？",
                "opts"   : ["if hp < 5: print('跑！')", "if hp > 5: print('跑！')",
                            "if hp = 5: print('跑！')", "if hp != 5: print('跑！')"],
                "ans"    : 1,
                "explain": "< 是小於符號，hp < 5 就是血量小於5。",
                "diff"   : 1,
            },
            {
                "q"      : "hp = 10\nif hp > 15:\n    print('滿血')\nelif hp > 5:\n    print('安全')\nelse:\n    print('危險')\n印出什麼？",
                "opts"   : ["滿血", "安全", "危險", "什麼都不印"],
                "ans"    : 2,
                "explain": "hp=10，不滿足 >15，但滿足 >5，所以執行 elif 印出「安全」。",
                "diff"   : 1,
            },
            {
                "q"      : "要「有劍 AND 有盾」才能打 Boss，用什麼運算子？",
                "opts"   : ["or", "not", "and", "+"],
                "ans"    : 3,
                "explain": "and 要求兩個條件都成立才為 True。",
                "diff"   : 1,
            },
            {
                "q"      : "哪個是「不等於」的比較運算子？",
                "opts"   : ["=", "==", "!=", "<>"],
                "ans"    : 3,
                "explain": "!= 是不等於。== 是比較相等（不是賦值的 =）。",
                "diff"   : 1,
            },
            {
                "q"      : "has_diamond = True\nif not has_diamond:\n    print('去挖鑽石！')\nelse:\n    print('可以打末影龍！')\n印出什麼？",
                "opts"   : ["去挖鑽石！", "可以打末影龍！", "True", "什麼都不印"],
                "ans"    : 2,
                "explain": "not True = False，所以 if 條件不成立，執行 else。",
                "diff"   : 2,
            },
            {
                "q"      : "if x > 3: print('diamond')\n哪個 x 的值會讓程式印出 diamond？",
                "opts"   : ["x = 1", "x = 3", "x = 4", "x = 0"],
                "ans"    : 3,
                "explain": "> 是嚴格大於，所以 x 必須 > 3，x=4 才符合條件。",
                "diff"   : 1,
            },
            {
                "q"      : "hp = 3\nfood = 1\nif hp <= 0 or food <= 0:\n    print('危險！')\n印出什麼？",
                "opts"   : ["危險！", "什麼都不印", "錯誤", "hp = 3"],
                "ans"    : 1,
                "explain": "food=1，1 <= 0 是 False；hp=3，3 <= 0 也是 False。但 or 只要一個 True，這裡 food<=0 是 False，hp<=0 也是 False，所以 False or False = False，不會印！\n等等讓我重新看：food=1，1<=0=False；hp=3，3<=0=False；False or False=False，所以不印！\n\n哎，題目出錯了，讓我重新設計... 其實這題的正確答案應該是「什麼都不印」，讓我修正。",
                "diff"   : 2,
            },
            {
                "q"      : "hp = 0\nif hp <= 0 or hp >= 100:\n    print('異常狀態！')\n印出什麼？",
                "opts"   : ["異常狀態！", "什麼都不印", "0", "錯誤"],
                "ans"    : 1,
                "explain": "hp=0，0 <= 0 是 True。or 只要有一個 True 就成立，所以印出「異常狀態！」。",
                "diff"   : 2,
            },
            {
                "q"      : "if 的程式區塊縮排要用幾個空格（Python 慣例）？",
                "opts"   : ["2 個空格", "4 個空格", "1 個 Tab（皆可，但要一致）", "不需要縮排"],
                "ans"    : 2,
                "explain": "Python 官方風格（PEP8）建議用 4 個空格。重要的是整個程式縮排要一致！",
                "diff"   : 1,
            },
            {
                "q"      : "name = 'Steve'\nif name == 'Steve':\n    print('英雄！')\nelse:\n    print('陌生人')\n印出什麼？",
                "opts"   : ["英雄！", "陌生人", "Steve", "name"],
                "ans"    : 1,
                "explain": "== 比較兩個值是否相等，'Steve' == 'Steve' 是 True，所以印「英雄！」。",
                "diff"   : 1,
            },
            {
                "q"      : "if 裡面還有 if，叫做什麼？",
                "opts"   : ["雙重 if", "巢狀 if（Nested if）", "elif", "多層條件"],
                "ans"    : 2,
                "explain": "if 裡面再放 if 叫「巢狀 if」（Nested if），可以做更細緻的判斷。",
                "diff"   : 2,
            },
            {
                "q"      : "x = 5\nif x > 3:\n    if x > 4:\n        print('鑽石！')\n    else:\n        print('金礦')\n印出什麼？",
                "opts"   : ["鑽石！", "金礦", "什麼都不印", "錯誤"],
                "ans"    : 1,
                "explain": "x=5，5>3 成立進入外層 if；5>4 也成立，印出「鑽石！」。",
                "diff"   : 3,
            },
        ],
    },

    # ──────────────────────────────────────────────────
    "for": {
        "title"     : "🔄  第四關：for 迴圈",
        "color_name": "green",
        "questions" : [
            {
                "q"      : "for i in range(5): 讓 i 跑過哪些數字？",
                "opts"   : ["1, 2, 3, 4, 5", "0, 1, 2, 3, 4",
                            "0, 1, 2, 3, 4, 5", "1, 2, 3, 4"],
                "ans"    : 2,
                "explain": "range(5) 從 0 開始，到 4 結束（不含 5），共 5 個數字。",
                "diff"   : 1,
            },
            {
                "q"      : "items = ['木頭', '石頭', '鑽石']\nfor item in items:\n    print(item)\n共印出幾行？",
                "opts"   : ["1 行", "2 行", "3 行", "0 行"],
                "ans"    : 3,
                "explain": "for 迴圈跑遍 list 裡每個元素，共 3 個，所以印 3 行。",
                "diff"   : 1,
            },
            {
                "q"      : "range(2, 10, 2) 產生哪些數字？",
                "opts"   : ["2, 4, 6, 8, 10", "2, 4, 6, 8",
                            "0, 2, 4, 6, 8", "2, 3, 4, 5, 6, 7, 8, 9"],
                "ans"    : 2,
                "explain": "range(start, stop, step)：從2開始，每次加2，到10之前停（不含10）。",
                "diff"   : 1,
            },
            {
                "q"      : "total = 0\nfor i in range(1, 4):\n    total += i\nprint(total)\n印出什麼？",
                "opts"   : ["3", "4", "6", "10"],
                "ans"    : 3,
                "explain": "range(1,4) 產生 1,2,3。1+2+3=6。",
                "diff"   : 2,
            },
            {
                "q"      : "在 for 迴圈中，哪個關鍵字「立刻跳出迴圈」？",
                "opts"   : ["continue", "pass", "stop", "break"],
                "ans"    : 4,
                "explain": "break 立刻終止整個迴圈。continue 是跳過這一次，繼續下一圈。",
                "diff"   : 1,
            },
            {
                "q"      : "for i in range(3):\n    print('挖！')\n共印出幾次「挖！」？",
                "opts"   : ["2 次", "3 次", "4 次", "0 次"],
                "ans"    : 2,
                "explain": "range(3) 產生 0,1,2，迴圈執行 3 次，所以印 3 次。",
                "diff"   : 1,
            },
            {
                "q"      : "continue 在 for 迴圈中的作用是？",
                "opts"   : ["跳出整個迴圈", "跳過這一圈，繼續下一圈",
                            "暫停迴圈", "重新開始迴圈"],
                "ans"    : 2,
                "explain": "continue 跳過目前這一次的剩餘程式碼，直接進入下一次迴圈。",
                "diff"   : 1,
            },
            {
                "q"      : "巢狀 for 迴圈：\nfor i in range(3):\n    for j in range(2):\n        print('X')\n共印出幾個 X？",
                "opts"   : ["2", "3", "5", "6"],
                "ans"    : 4,
                "explain": "外層跑 3 次，每次內層跑 2 次，共 3×2=6 次。",
                "diff"   : 2,
            },
            {
                "q"      : "range(1, 11) 包含哪些數字？",
                "opts"   : ["0 到 11", "1 到 10", "1 到 11", "0 到 10"],
                "ans"    : 2,
                "explain": "range(start, stop) 包含 start，不包含 stop。所以是 1 到 10。",
                "diff"   : 1,
            },
            {
                "q"      : "ore_count = 0\nores = [3, 15, 2, 8, 11]\nfor ore in ores:\n    if ore > 10:\n        ore_count += 1\nprint(ore_count)\n印出什麼？",
                "opts"   : ["1", "2", "3", "5"],
                "ans"    : 2,
                "explain": "大於10的有 15 和 11，共 2 個，所以 ore_count=2。",
                "diff"   : 2,
            },
            {
                "q"      : "for i in range(5):\n    if i == 3:\n        break\n    print(i)\n最後印出哪些數字？",
                "opts"   : ["0 1 2 3 4", "0 1 2 3", "0 1 2", "1 2 3"],
                "ans"    : 3,
                "explain": "i=0,1,2 時印出，i=3 時執行 break 跳出，所以只印 0,1,2。",
                "diff"   : 2,
            },
            {
                "q"      : "for i in range(1, 6):\n    if i % 2 == 0:\n        continue\n    print(i)\n印出哪些數字？",
                "opts"   : ["1 3 5", "2 4", "1 2 3 4 5", "1 3"],
                "ans"    : 1,
                "explain": "% 是取餘數。i%2==0 代表偶數，偶數時 continue 跳過不印，所以只印奇數 1,3,5。",
                "diff"   : 3,
            },
        ],
    },

    # ──────────────────────────────────────────────────
    "while": {
        "title"     : "🔁  第五關：while 迴圈",
        "color_name": "purple",
        "questions" : [
            {
                "q"      : "hp = 5\nwhile hp > 0:\n    hp -= 2\nprint(hp)\nhp 最後是多少？",
                "opts"   : ["0", "-1", "1", "5"],
                "ans"    : 2,
                "explain": "hp: 5→3→1→-1。hp=-1 時 hp>0 為 False，離開迴圈。",
                "diff"   : 2,
            },
            {
                "q"      : "while True: 是什麼意思？",
                "opts"   : ["只執行一次", "永遠不執行",
                            "無限迴圈（除非 break）", "語法錯誤"],
                "ans"    : 3,
                "explain": "while True 條件永遠成立，會無限執行，通常搭配 break 結束。",
                "diff"   : 1,
            },
            {
                "q"      : "哪種情況更適合用 while 而非 for？",
                "opts"   : ["已知要跑 10 次", "跑遍一個 list",
                            "不知道要跑幾次，直到條件成立才停", "計算 1 到 100 的總和"],
                "ans"    : 3,
                "explain": "while 適合「不確定次數」的情況，例如：一直問直到輸入正確。",
                "diff"   : 1,
            },
            {
                "q"      : "i = 0\nwhile i < 5:\n    i += 1\n    if i == 3:\n        continue\n    print(i)\n印出哪些數字？",
                "opts"   : ["1 2 3 4 5", "1 2 4 5", "1 2 3 4", "0 1 2 4 5"],
                "ans"    : 2,
                "explain": "i==3 時 continue 跳過 print，所以 3 不印，印出 1,2,4,5。",
                "diff"   : 2,
            },
            {
                "q"      : "殭屍 hp=10，玩家每次攻擊扣3點，需要幾次才打倒殭屍？",
                "opts"   : ["3 次", "4 次", "5 次", "10 次"],
                "ans"    : 2,
                "explain": "10→7→4→1→-2，第4次後 hp=-2 ≤ 0，需要 4 次。",
                "diff"   : 2,
            },
            {
                "q"      : "while 迴圈什麼時候停止？",
                "opts"   : ["程式執行了 100 次", "條件變成 False 的時候",
                            "遇到 print()", "程式執行完所有的行"],
                "ans"    : 2,
                "explain": "while 在每次執行前檢查條件，條件為 False 時停止。",
                "diff"   : 1,
            },
            {
                "q"      : "count = 0\nwhile count < 3:\n    print('挖礦！')\n    count += 1\n共印出幾次「挖礦！」？",
                "opts"   : ["2 次", "3 次", "4 次", "無限次"],
                "ans"    : 2,
                "explain": "count: 0→1→2→3，count=3 時條件 <3 為 False，停止。共執行 3 次。",
                "diff"   : 1,
            },
            {
                "q"      : "以下程式有什麼問題？\ni = 0\nwhile i < 5:\n    print(i)",
                "opts"   : ["語法錯誤", "無限迴圈（忘了增加 i）",
                            "只會印出 0", "正常執行印出 0 到 4"],
                "ans"    : 2,
                "explain": "i 永遠是 0，條件 i < 5 永遠為 True，造成無限迴圈！要加 i += 1。",
                "diff"   : 2,
            },
            {
                "q"      : "用 while 讓玩家一直輸入，直到輸入 'quit' 才停，哪個結構正確？",
                "opts"   : ["while input != 'quit':",
                            "while True: cmd = input(); if cmd == 'quit': break",
                            "for cmd in input():",
                            "if input() != 'quit': while True:"],
                "ans"    : 2,
                "explain": "while True + break 是「先執行、再判斷是否停」的常見模式。",
                "diff"   : 2,
            },
            {
                "q"      : "hp = 20\ndmg = 7\nrounds = 0\nwhile hp > 0:\n    hp -= dmg\n    rounds += 1\nprint(rounds)\n印出什麼？",
                "opts"   : ["2", "3", "4", "5"],
                "ans"    : 2,
                "explain": "20→13→6→-1，第3次後 hp=-1 ≤ 0，rounds=3。",
                "diff"   : 3,
            },
            {
                "q"      : "while 跟 for 最大的共同點是什麼？",
                "opts"   : ["都只能執行固定次數", "都是重複執行程式碼的迴圈",
                            "都需要 range()", "都不能使用 break"],
                "ans"    : 2,
                "explain": "while 和 for 都是迴圈結構，都用於重複執行程式碼，只是觸發條件不同。",
                "diff"   : 1,
            },
            {
                "q"      : "n = 1\nwhile n < 100:\n    n *= 2\nprint(n)\n印出什麼？",
                "opts"   : ["64", "128", "100", "256"],
                "ans"    : 2,
                "explain": "n: 1→2→4→8→16→32→64→128。n=128 時 128 < 100 為 False，停止，印出 128。",
                "diff"   : 3,
            },
        ],
    },

    # ──────────────────────────────────────────────────
    "list": {
        "title"     : "🎒  第六關：串列 List",
        "color_name": "cyan",
        "questions" : [
            {
                "q"      : 'bag = ["木頭", "石頭", "鑽石"]\nbag[1] 是什麼？',
                "opts"   : ["木頭", "石頭", "鑽石", "錯誤"],
                "ans"    : 2,
                "explain": "List 索引從 0 開始。bag[0]=木頭, bag[1]=石頭, bag[2]=鑽石。",
                "diff"   : 1,
            },
            {
                "q"      : 'bag = ["木頭", "石頭"]\nbag.append("鑽石")\nlen(bag) 是多少？',
                "opts"   : ["1", "2", "3", "4"],
                "ans"    : 3,
                "explain": "append() 加到 list 尾巴，原本 2 個加上 1 個變 3 個。",
                "diff"   : 1,
            },
            {
                "q"      : '哪個可以檢查 "鑽石" 是不是在 bag 裡？',
                "opts"   : ["bag.find('鑽石')", '"鑽石" in bag',
                            "bag.has('鑽石')", "bag.contains('鑽石')"],
                "ans"    : 2,
                "explain": "Python 用 in 運算子檢查元素是否在 list 裡，很直觀！",
                "diff"   : 1,
            },
            {
                "q"      : 'bag = ["木頭","石頭","鑽石","金礦"]\nbag[1:3] 是什麼？',
                "opts"   : ['["木頭", "石頭"]', '["石頭", "鑽石"]',
                            '["石頭", "鑽石", "金礦"]', '["木頭", "石頭", "鑽石"]'],
                "ans"    : 2,
                "explain": "切片 [1:3] 取索引 1 到 2（不含 3），所以是石頭和鑽石。",
                "diff"   : 2,
            },
            {
                "q"      : 'bag = ["木頭", "石頭", "鑽石"]\nbag.remove("石頭") 後，bag 是？',
                "opts"   : ['["木頭", "鑽石"]', '["石頭", "鑽石"]',
                            '["木頭", "石頭"]', '["木頭"]'],
                "ans"    : 1,
                "explain": "remove() 從 list 中刪除指定的元素，石頭被移除，剩木頭和鑽石。",
                "diff"   : 1,
            },
            {
                "q"      : 'bag = ["木頭", "石頭", "鑽石"]\nbag[-1] 是什麼？',
                "opts"   : ["木頭", "石頭", "鑽石", "錯誤"],
                "ans"    : 3,
                "explain": "負數索引從末尾數起，bag[-1] 是最後一個元素，也就是鑽石。",
                "diff"   : 2,
            },
            {
                "q"      : 'bag = []\nbag.append("劍")\nbag.append("盾")\nlen(bag) 是多少？',
                "opts"   : ["0", "1", "2", "3"],
                "ans"    : 3,
                "explain": "空 list 加入劍再加入盾，共 2 個元素，len(bag) = 2。",
                "diff"   : 1,
            },
            {
                "q"      : 'bag = ["木頭", "石頭", "鑽石"]\nbag.pop() 後，bag 是？',
                "opts"   : ['["木頭", "石頭", "鑽石"]',
                            '["石頭", "鑽石"]',
                            '["木頭", "石頭"]',
                            '["鑽石"]'],
                "ans"    : 3,
                "explain": "pop() 不給參數時，移除並回傳最後一個元素（鑽石），剩木頭和石頭。",
                "diff"   : 2,
            },
            {
                "q"      : "items = [5, 2, 8, 1]\nitems.sort()\nprint(items)\n印出什麼？",
                "opts"   : ["[5, 2, 8, 1]", "[1, 2, 5, 8]",
                            "[8, 5, 2, 1]", "錯誤"],
                "ans"    : 2,
                "explain": ".sort() 會把 list 由小到大排序（原地修改）。",
                "diff"   : 2,
            },
            {
                "q"      : 'bag = ["木頭", "石頭"]\nbag[0] = "鑽石"\nprint(bag)\n印出什麼？',
                "opts"   : ['["木頭", "石頭"]', '["鑽石", "石頭"]',
                            '["木頭", "鑽石"]', "錯誤"],
                "ans"    : 2,
                "explain": "bag[0] = '鑽石' 把索引 0 的元素（木頭）換成鑽石。",
                "diff"   : 2,
            },
            {
                "q"      : 'a = [1, 2]\nb = [3, 4]\nprint(a + b)\n印出什麼？',
                "opts"   : ["[4, 6]", "[1, 2, 3, 4]", "[3, 4, 1, 2]", "錯誤"],
                "ans"    : 2,
                "explain": "兩個 list 相加，會把元素合併成一個新 list（不是數字相加）。",
                "diff"   : 2,
            },
            {
                "q"      : 'bag = []\nif not bag:\n    print("背包是空的")\n印出什麼？',
                "opts"   : ["背包是空的", "什麼都不印", "False", "[]"],
                "ans"    : 1,
                "explain": "空的 list 在 if 判斷中視為 False，not [] = True，所以印出「背包是空的」。",
                "diff"   : 3,
            },
        ],
    },

    # ──────────────────────────────────────────────────
    "function": {
        "title"     : "🔧  第七關：函式 Function",
        "color_name": "yellow",
        "questions" : [
            {
                "q"      : "定義一個函式要用哪個關鍵字？",
                "opts"   : ["function", "func", "def", "define"],
                "ans"    : 3,
                "explain": "Python 用 def 來定義函式，後面接函式名稱和括號。",
                "diff"   : 1,
            },
            {
                "q"      : "def greet(name):\n    print(f'Hello, {name}!')\ngreet('Steve') 印出什麼？",
                "opts"   : ["Hello, name!", "Hello, {name}!",
                            "Hello, Steve!", "greet('Steve')"],
                "ans"    : 3,
                "explain": "name 是參數，呼叫時傳入 'Steve'，f-string 替換後印出 Hello, Steve!",
                "diff"   : 1,
            },
            {
                "q"      : "def damage(attack, defense):\n    return attack - defense\nprint(damage(10, 3)) 印出什麼？",
                "opts"   : ["10", "3", "7", "13"],
                "ans"    : 3,
                "explain": "10 - 3 = 7，return 回傳結果，print() 印出 7。",
                "diff"   : 1,
            },
            {
                "q"      : "函式中的 return 的作用是？",
                "opts"   : ["印出一個值", "把值回傳給呼叫者",
                            "重複執行函式", "結束整個程式"],
                "ans"    : 2,
                "explain": "return 把值傳回去，讓呼叫函式的地方可以使用這個結果。",
                "diff"   : 1,
            },
            {
                "q"      : "為什麼要把程式碼寫成函式？",
                "opts"   : ["讓程式跑更快",
                            "可以重複使用，避免重複寫同樣的程式碼",
                            "Python 規定一定要用函式",
                            "函式讓程式佔更少記憶體"],
                "ans"    : 2,
                "explain": "函式讓你把一段邏輯包起來，需要時呼叫即可，不用重複寫。",
                "diff"   : 1,
            },
            {
                "q"      : "def say_hi():\n    print('Hi!')\n\nresult = say_hi()\nprint(result)\n印出什麼？",
                "opts"   : ["Hi!", "Hi!\nNone", "None", "錯誤"],
                "ans"    : 2,
                "explain": "say_hi() 印出 Hi!，但沒有 return，所以 result = None，接著印 None。",
                "diff"   : 2,
            },
            {
                "q"      : "def greet(name='Steve'):\n    print(f'Hi, {name}!')\ngreet() 印出什麼？",
                "opts"   : ["Hi, !", "Hi, name!", "Hi, Steve!", "錯誤"],
                "ans"    : 3,
                "explain": "name='Steve' 是預設參數。呼叫時不傳入就用預設值 Steve。",
                "diff"   : 2,
            },
            {
                "q"      : "def add(a, b):\n    return a + b\n\nprint(add(3, add(1, 2)))\n印出什麼？",
                "opts"   : ["3", "6", "5", "錯誤"],
                "ans"    : 2,
                "explain": "先算內層 add(1,2)=3，再算外層 add(3,3)=6。",
                "diff"   : 3,
            },
            {
                "q"      : "函式參數（parameter）是什麼？",
                "opts"   : ["函式的回傳值",
                            "呼叫函式時傳入的資訊（括號裡的變數）",
                            "函式裡的所有程式碼",
                            "def 關鍵字"],
                "ans"    : 2,
                "explain": "參數是函式定義時括號內的變數，用來接收呼叫時傳入的資料。",
                "diff"   : 1,
            },
            {
                "q"      : "def is_alive(hp):\n    return hp > 0\n\nprint(is_alive(5))\n印出什麼？",
                "opts"   : ["5", "0", "True", "False"],
                "ans"    : 3,
                "explain": "5 > 0 是 True，return True，print(True) 印出 True。",
                "diff"   : 2,
            },
            {
                "q"      : "def craft(wood, stone):\n    if wood >= 2 and stone >= 3:\n        return '石劍'\n    return '材料不夠'\n\nprint(craft(3, 2)) 印出什麼？",
                "opts"   : ["石劍", "材料不夠", "True", "錯誤"],
                "ans"    : 2,
                "explain": "wood=3 ≥ 2，但 stone=2 不 ≥ 3，and 條件不成立，執行 return '材料不夠'。",
                "diff"   : 3,
            },
            {
                "q"      : "def double(x):\n    return x * 2\n\nresult = double(double(3))\nprint(result)\n印出什麼？",
                "opts"   : ["3", "6", "9", "12"],
                "ans"    : 4,
                "explain": "先算內層 double(3)=6，再算外層 double(6)=12。",
                "diff"   : 3,
            },
        ],
    },

    # ──────────────────────────────────────────────────
    "mixed": {
        "title"     : "🏆  BOSS關：for + if + while 混合！",
        "color_name": "purple",
        "questions" : [
            {
                "q"      : "items = [5, 12, 3, 8, 1]\ncount = 0\nfor x in items:\n    if x > 4:\n        count += 1\nprint(count)\n印出什麼？",
                "opts"   : ["1", "2", "3", "5"],
                "ans"    : 3,
                "explain": "大於4的有 5, 12, 8，共 3 個，count=3。",
                "diff"   : 2,
            },
            {
                "q"      : "bag = ['木頭','石頭','鑽石','鐵礦','鑽石']\ndiamonds = 0\nfor item in bag:\n    if item == '鑽石':\n        diamonds += 1\nprint(diamonds)\n印出什麼？",
                "opts"   : ["0", "1", "2", "3"],
                "ans"    : 3,
                "explain": "bag 裡有兩個 '鑽石'，diamonds 加了兩次，結果是 2。",
                "diff"   : 2,
            },
            {
                "q"      : "hp = 20\nattacks = [5, 8, 3, 7]\nfor dmg in attacks:\n    hp -= dmg\n    if hp <= 0:\n        print('死了！')\n        break\nSteve 在第幾次攻擊後死？",
                "opts"   : ["第2次", "第3次", "第4次", "不會死"],
                "ans"    : 3,
                "explain": "20-5=15, 15-8=7, 7-3=4, 4-7=-3 ≤ 0，第4次攻擊後 break，印「死了！」。",
                "diff"   : 2,
            },
            {
                "q"      : "ores = [3, 7, 12, 4, 15]\nfor ore in ores:\n    if ore > 10:\n        print(ore)\n        break\n印出什麼？",
                "opts"   : ["7", "12", "15", "12 和 15 都印"],
                "ans"    : 2,
                "explain": "找到 12 就 break，不繼續，所以只印 12。",
                "diff"   : 2,
            },
            {
                "q"      : "def fight(hp, damage, rounds):\n    for i in range(rounds):\n        hp -= damage\n        if hp <= 0:\n            return '死亡'\n    return '存活'\nprint(fight(10, 3, 4))\n印出什麼？",
                "opts"   : ["存活", "死亡", "10", "錯誤"],
                "ans"    : 2,
                "explain": "10→7→4→1→-2，第4次後 return '死亡'。",
                "diff"   : 3,
            },
            {
                "q"      : "bag = []\ni = 0\nwhile i < 3:\n    bag.append('鑽石')\n    i += 1\nprint(len(bag))\n印出什麼？",
                "opts"   : ["0", "1", "3", "4"],
                "ans"    : 3,
                "explain": "while 跑 3 次（i=0,1,2），每次加一個鑽石，最後 bag 有 3 個元素。",
                "diff"   : 2,
            },
            {
                "q"      : "nums = [1, 2, 3, 4, 5]\ntotal = 0\nfor n in nums:\n    if n % 2 == 0:\n        continue\n    total += n\nprint(total)\n印出什麼？（只加奇數）",
                "opts"   : ["6", "9", "15", "10"],
                "ans"    : 2,
                "explain": "偶數（2,4）被 continue 跳過，只加奇數 1+3+5=9。",
                "diff"   : 3,
            },
            {
                "q"      : "def count_diamonds(bag):\n    count = 0\n    for item in bag:\n        if item == '鑽石':\n            count += 1\n    return count\n\nprint(count_diamonds(['石頭','鑽石','木頭']))\n印出什麼？",
                "opts"   : ["0", "1", "2", "3"],
                "ans"    : 2,
                "explain": "bag 裡只有一個 '鑽石'，count=1，函式回傳 1，print 印 1。",
                "diff"   : 2,
            },
            {
                "q"      : "count = 0\nfor i in range(3):\n    for j in range(3):\n        if i == j:\n            count += 1\nprint(count)\n印出什麼？",
                "opts"   : ["3", "6", "9", "0"],
                "ans"    : 1,
                "explain": "i==j 的情況：(0,0), (1,1), (2,2)，共 3 次，count=3。",
                "diff"   : 3,
            },
            {
                "q"      : "items = [10, 3, 7, 15, 2]\nmax_val = items[0]\nfor item in items:\n    if item > max_val:\n        max_val = item\nprint(max_val)\n印出什麼？",
                "opts"   : ["10", "3", "15", "7"],
                "ans"    : 3,
                "explain": "這是找最大值的演算法。跑完所有元素後，max_val=15。",
                "diff"   : 2,
            },
            {
                "q"      : "def level_up(xp):\n    level = 1\n    while xp >= 100:\n        xp -= 100\n        level += 1\n    return level\n\nprint(level_up(350))\n印出什麼？",
                "opts"   : ["3", "4", "5", "350"],
                "ans"    : 2,
                "explain": "350→250(lv2)→150(lv3)→50(lv4)。50 < 100 停止，回傳 level=4。",
                "diff"   : 3,
            },
            {
                "q"      : "bag = ['木頭', '石頭', '木頭', '鑽石']\nunique = []\nfor item in bag:\n    if item not in unique:\n        unique.append(item)\nprint(len(unique))\n印出什麼？（去除重複）",
                "opts"   : ["2", "3", "4", "1"],
                "ans"    : 2,
                "explain": "木頭只加一次，去除重複後 unique=['木頭','石頭','鑽石']，共 3 個。",
                "diff"   : 3,
            },
        ],
    },
}

# 章節播放順序（老師依此順序解鎖）
CHAPTER_ORDER = [
    "variables",
    "io",
    "if",
    "for",
    "while",
    "list",
    "function",
    "mixed",
]
